export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_CLOTHES = "FETCH_PRODUCTS_CLOTHES";
export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CURRENCY_CHANGE = "CURRENCY_CHANGE";
export const FETCH_PRODUCTS_TECH = "FETCH_PRODUCTS_TECH";
